language: node_js
cache: yarn
script:
  - yarn --version
  - yarn check --integrity
  - yarn lint
  - yarn test
  - yarn test:coverage
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
  - yarn test:codacy-upload
  - yarn test:codecov-upload
deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: jQWWsCteAFyjg8gUFg/FbGVDr9u5a5b1kyav7nEtjXep+vQXApJ0MnBY53GVXBcCeatnlIOpMYVSE/YY6IljZKS/85diIIBGBRVO0t/PrZmez0+btFCWoub/+jNd/KQt4Si1GKH1Et737lPsN3rrD+LP/4OQc6QOxeM37AlYP4x2jhe/dQGQWOwya8XpV+HVkuSe6hgd0eF6wIXXrYLP1tp+cY4WqSu+8YtcNlSySnaW4pAUq1snWK455HQiO9nKIwnF9MwP1W2BMijUQI5FMfxaJXAjBs4bnkR+8/QJ0esWkbW2pqX2ZVszfqxmdJ21l0hhSXfq5kEgBTHfP8Gp5sGLCc4mJBIYRwY3Ow0C4Srk4uUSfiFBw6y3HcEhUud5bjb1j8vPQ0x3HQWPMq0goadKk1SG6KqINSfOjzLzCGAXvbl5cw5QDUQ65FXKlWSsDmUPZvF3lWqfAVvsWs7S/T1JHpJlN/dS/iHL6Zs3/avfsHPMc3VRZQhXis6PqhCplnT7cdi2MRM9Wm3Q3gddUTpNZ7V+3SJnHOCNZ9jFStAIgok2I870fzuXOccHsllxCdiZyyKuauKW37ZKYu3bB9PT1zmk5F2FBghDQUwgDc/b63Agj56OVyxAOaWZb51C/d30KSzsMutX6ffRI5rfaaqwDtK7RZvBo7EH8jVyFhc=
  on:
    tags: true
    repo: hmcts/cmc-draft-store-middleware
